"""added unique constraint of user id and account type to customers table 1

Revision ID: 0c3901b96d02
Revises: 1d1dd2f253e6
Create Date: 2025-04-01 23:28:19.237614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0c3901b96d02'
down_revision: Union[str, None] = '1d1dd2f253e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Customers', 'AccountTypeId',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('UserId', table_name='Customers')
    op.create_foreign_key(None, 'Customers', 'AccountTypes', ['AccountTypeId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customers', type_='foreignkey')
    op.create_index('UserId', 'Customers', ['UserId'], unique=True)
    op.alter_column('Customers', 'AccountTypeId',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
