"""added unique constraint of user id and account type to customers table

Revision ID: 1d1dd2f253e6
Revises: dbf157da90f6
Create Date: 2025-04-01 23:16:12.500449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d1dd2f253e6'
down_revision: Union[str, None] = 'dbf157da90f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_accounttype', 'Customers', ['UserId', 'AccountTypeId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_accounttype', 'Customers', type_='unique')
    # ### end Alembic commands ###
