"""modified models

Revision ID: 47f05344effc
Revises: 
Create Date: 2025-04-01 17:26:28.356272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f05344effc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AccountTypes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Type')
    )
    op.create_table('Roles',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('TransactionModes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('TransactionStatuses',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('TransactionTypes',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('Users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LastName', sa.String(length=100), nullable=False),
    sa.Column('FirstName', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('RoleId', sa.Integer(), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['RoleId'], ['Roles.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Customers',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('AccountTypeid', sa.Integer(), nullable=True),
    sa.Column('Balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserId')
    )
    op.create_table('Staff',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=False),
    sa.Column('Position', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['UserId'], ['Users.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('UserId')
    )
    op.create_table('Transactions',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerId', sa.Integer(), nullable=False),
    sa.Column('AccountTypeId', sa.Integer(), nullable=True),
    sa.Column('Account_Number', sa.String(length=10), nullable=True),
    sa.Column('TransactionTypeId', sa.Integer(), nullable=False),
    sa.Column('TransactionModeId', sa.Integer(), nullable=False),
    sa.Column('TransactionStatusId', sa.Integer(), nullable=False),
    sa.Column('Amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TransactionDate', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['CustomerId'], ['Customers.Id'], ),
    sa.ForeignKeyConstraint(['TransactionModeId'], ['TransactionModes.Id'], ),
    sa.ForeignKeyConstraint(['TransactionStatusId'], ['TransactionStatuses.Id'], ),
    sa.ForeignKeyConstraint(['TransactionTypeId'], ['TransactionTypes.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    op.drop_table('Staff')
    op.drop_table('Customers')
    op.drop_table('Users')
    op.drop_table('TransactionTypes')
    op.drop_table('TransactionStatuses')
    op.drop_table('TransactionModes')
    op.drop_table('Roles')
    op.drop_table('AccountTypes')
    # ### end Alembic commands ###
