"""Add description column to TransactionTypes

Revision ID: 61e93fcb9b9f
Revises: e8e2a6d41b0a
Create Date: 2025-04-01 14:04:37.274587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e93fcb9b9f'
down_revision: Union[str, None] = 'e8e2a6d41b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
