"""Add description column to TransactionTypes

Revision ID: 661832db22c0
Revises: 149509a30a8a
Create Date: 2025-04-01 16:30:27.507857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '661832db22c0'
down_revision: Union[str, None] = '149509a30a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TransactionTypes', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TransactionTypes', 'description')
    # ### end Alembic commands ###
