"""Removed customer id from Accounts table

Revision ID: 6d821452d181
Revises: 9bff03b967f4
Create Date: 2025-04-28 01:57:51.856977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d821452d181'
down_revision: Union[str, None] = '9bff03b967f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # op.drop_constraint('Accounts_ibfk_2', 'Accounts', type_='foreignkey')
    # op.drop_index('uq_customer_account_type', table_name='Accounts')
    # op.drop_column('Accounts', 'CustomerId')
    # op.create_unique_constraint('uq_user_account_type', 'Accounts', ['UserId', 'AccountTypeId'])
    # op.create_foreign_key(None, 'Accounts', 'Users', ['UserId'], ['Id'])
    # op.create_foreign_key(None, 'Transactions', 'Users', ['UserId'], ['Id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'Transactions', type_='foreignkey')
    # op.add_column('Accounts', sa.Column('CustomerId', mysql.INTEGER(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'Accounts', type_='foreignkey')
    # op.create_foreign_key('Accounts_ibfk_2', 'Accounts', 'Customers', ['CustomerId'], ['Id'])
    # op.drop_constraint('uq_user_account_type', 'Accounts', type_='unique')
    # op.create_index('uq_customer_account_type', 'Accounts', ['CustomerId', 'AccountTypeId'], unique=True)
    # ### end Alembic commands ###
