"""Add description column to TransactionTypes

Revision ID: 9990b5cb2f90
Revises: 217c70cf71e3
Create Date: 2025-04-01 13:55:56.723199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9990b5cb2f90'
down_revision: Union[str, None] = '217c70cf71e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TransactionTypes', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TransactionTypes', 'description')
    # ### end Alembic commands ###
