"""Add UserId to accounts table

Revision ID: 9bff03b967f4
Revises: ffad81f7dd96
Create Date: 2025-04-27 21:51:10.829760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bff03b967f4'
down_revision: Union[str, None] = 'ffad81f7dd96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Accounts', sa.Column('UserId', sa.Integer(), nullable=False))
    # op.create_unique_constraint('uq_user_account_type', 'Accounts', ['UserId', 'AccountTypeId'])
    # op.create_foreign_key(None, 'Accounts', 'Users', ['UserId'], ['Id'])
    # op.create_foreign_key(None, 'Transactions', 'Users', ['UserId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'Transactions', type_='foreignkey')
    # op.drop_constraint(None, 'Accounts', type_='foreignkey')
    # op.drop_constraint('uq_user_account_type', 'Accounts', type_='unique')
    # op.drop_column('Accounts', 'UserId')
    # ### end Alembic commands ###
