"""Removed customer id from customer service and queries

Revision ID: a7f33819c47a
Revises: 6d821452d181
Create Date: 2025-04-28 02:48:24.978431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f33819c47a'
down_revision: Union[str, None] = '6d821452d181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_account_type', 'Accounts', ['UserId', 'AccountTypeId'])
    op.create_foreign_key(None, 'Accounts', 'Users', ['UserId'], ['Id'])
    op.create_foreign_key(None, 'Transactions', 'Users', ['UserId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.drop_constraint(None, 'Accounts', type_='foreignkey')
    op.drop_constraint('uq_user_account_type', 'Accounts', type_='unique')
    # ### end Alembic commands ###
