"""Remove description from TransactionTypes

Revision ID: b6bae2b9cf81
Revises: 9990b5cb2f90
Create Date: 2025-04-01 13:58:38.440058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6bae2b9cf81'
down_revision: Union[str, None] = '9990b5cb2f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TransactionTypes', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TransactionTypes', sa.Column('description', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    # ### end Alembic commands ###
