"""added active, created at and updated at to the users table

Revision ID: dbf157da90f6
Revises: dc7af22b238b
Create Date: 2025-04-01 22:40:55.439150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbf157da90f6'
down_revision: Union[str, None] = 'dc7af22b238b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('Active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('Users', sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Users', sa.Column('UpdatedAt', mysql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'UpdatedAt')
    op.drop_column('Users', 'CreatedAt')
    op.drop_column('Users', 'Active')
    # ### end Alembic commands ###
