"""move account number to customer

Revision ID: dc7af22b238b
Revises: 47f05344effc
Create Date: 2025-04-01 17:56:43.510474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7af22b238b'
down_revision: Union[str, None] = '47f05344effc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Customers', sa.Column('AccountNumber', sa.String(length=10), nullable=False))
    op.add_column('Customers', sa.Column('Address', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'Customers', ['AccountNumber'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Customers', type_='unique')
    op.drop_column('Customers', 'Address')
    op.drop_column('Customers', 'AccountNumber')
    # ### end Alembic commands ###
