"""added user navigation in customer table

Revision ID: ea203b96ef5a
Revises: 08bd3a5e7ed2
Create Date: 2025-04-10 12:56:22.684922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea203b96ef5a'
down_revision: Union[str, None] = '08bd3a5e7ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'CreatedAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Users', 'UpdatedAt',
               existing_type=mysql.DATETIME(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'UpdatedAt',
               existing_type=mysql.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('Users', 'CreatedAt',
               existing_type=mysql.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
