"""add sender id to transactions

Revision ID: eacc13f7804f
Revises: a7f33819c47a
Create Date: 2025-04-28 12:46:42.369176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacc13f7804f'
down_revision: Union[str, None] = 'a7f33819c47a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('SenderId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Transactions', 'Users', ['SenderId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.drop_column('Transactions', 'SenderId')
    # ### end Alembic commands ###
