"""Add UserId to Transactions table

Revision ID: ffad81f7dd96
Revises: 79f8d9a684b4
Create Date: 2025-04-26 09:26:09.614084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffad81f7dd96'
down_revision: Union[str, None] = '79f8d9a684b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('UserId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Transactions', 'Users', ['UserId'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Transactions', type_='foreignkey')
    op.drop_column('Transactions', 'UserId')
    # ### end Alembic commands ###
